version: '3'

networks:
  ruoyi_net:

services:
  # docker pull mysql:5.7.40
  # docker run -p 3307:3306 --name mysql --privileged=true -e MYSQL_ROOT_PASSWORD=mysql666 -d mysql:5.7.40
  mysql:
    image: mysql:5.7.40
    container_name: ruoyi-mysql
    ports:
      - '3306:3306'
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql666'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # 启动SQL脚本
    restart: always
    networks:
      - ruoyi_net

  # docker pull redis:6.0.8
  # docker run -p 6380:6379 --name redis --privileged=true -d redis:6.0.8 --requirepass "redis666"
  redis:
    image: redis:6.0.8
    container_name: ruoyi-redis
    ports:
      - '6379:6379'
    privileged: true
    command: --requirepass "redis666"
    restart: always
    networks:
      - ruoyi_net
